### PR TITLE
fix decap and rot13

### PR DESCRIPTION
**Pull request by TessHuelskamp**

### CODE REVIEW

**Comment by TessHuelskamp** [comment]
@bocajnotnef

**Comment by SensibleSalmon** [comment]
I'll look tonight

**Comment by TessHuelskamp** [comment]
Hi

**Review by SensibleSalmon — APPROVED** [review]
seems rainsable

only 6 months late on the review ✋

**Comment by TessHuelskamp** [comment]
Still better than some places I've worked 😛

Now I just need to get write access to merge this so that'll take another 6 months 😂

**Pull request merged**
